repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 84e478bc42d27f9c214de50dd331ca7602beb2f1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 3b03191b6a60cba0fc25c2dc2e30ea4854d897eb
    hooks:
      - id: clang-format
        args: ["-i", "--style=file:.clang-format"]
        exclude: 'compile_commands.json'
