(display (list 1 2 3))
(display (list 1))
(display (list))
(display (car (list 1 2 3)))
(display (car (list 1)))
(display (cdr (list 1 2 3)))
(display (cdr (list 1)))
(display (first (list 1 2 3)))
(display (first (list 1)))
(display (first (list)))
(display (last (list 1 2 3)))
(display (last (list 1)))
(display (last (list)))