(display (and))
(display (and #t))
(display (and #f))
(display (and #f #f))
(display (and #f #t))
(display (and #t #f))
(display (and #t #t))
(and #f (display (quote (You should not be seeing this))))
(and (display 1) (display 2) (display 3))
(and #f (display 1) (display 2) (display 3))
(display (and (display 1) (display 2) (display 3) #f))

(display (or))
(display (or #t))
(display (or #f))
(display (or #f #f))
(display (or #f #t))
(display (or #t #f))
(display (or #t #t))
(or #t (display (quote (You should not be seeing this))))
(or (not (display 1)) (not (display 2)) (not (display 3)))
(or #t (not (display 1)) (not (display 2)) (not (display 3)))
(or (not (display 1)) (not (display 2)) (not (display 3)) #t)
(display (or #f 1 #f 2))
