(display (and))
(display (and #t))
(display (and #f))
(display (and #f #f))
(display (and #f #t))
(display (and #t #f))
(display (and #t #t))
(and #f (display (quote (You should not be seeing this))))
(and (display 1) (display 2) (display 3) (define zero 0))
(display zero)
(set! zero 0)
(and #f (display 1) (display 2) (display 3) (define zero 0))
(and (display 1) (display 2) (display 3) #f (define zero 0))

(display (or))
(display (or #t))
(display (or #f))
(display (or #f #f))
(display (or #f #t))
(display (or #t #f))
(display (or #t #t))
(or #t (display (quote (You should not be seeing this))))
(or (not (display 1)) (not (display 2)) (not (display 3)) (not (define one 1)))
(display one)
(set! one 1)
(or #t (not (display 1)) (not (display 2)) (not (display 3)) (define zero 0))
(or (not (display 1)) (not (display 2)) (not (display 3)) #t (define zero 0))
(display (or #f 1 #f 2))
