(display (+ 1))
(display (+ -1))
(display (+ 1 1))
(display (+ 1 0 1))
(display (- 1))
(display (- -1))
(display (- 1 1))
(display (- 1 0 1))
(display (* 1))
(display (* -1))
(display (* 1 1))
(display (* 1 0 1))
(display (* 1 2))
(display (/ 1))
(display (/ -1))
(display (/ 1 1))
(display (/ 2 2 1))
(display (/ 1 -1))
(display (/ 1 -1 -1))
(display (abs 1))
(display (abs 0))
(display (abs -1))
(display (% 1 1))
(display (% 3 2))
(display (% 7 4))
