(display (null? (list)))
(display (null? '()))
(display (null? (list 1)))
(display (null? 1))
(display (pair? (cons 1 1)))
(display (pair? (list 1 2 3)))
(display (pair? (cdr (list 1 2 3))))
(display (pair? (cdr (list 1))))
(display (pair? (list)))
(display (sym? (quote x)))
(display (sym?  'x))
(define x (quote x))
(display (sym? x))
(display (num? 1))
(display (num? (+ 1 2)))
(define n 0)
(display (num? n))
(display (num? (lambda () (quote ()))))
(display (num? (list 1)))
(display (procedure? list))
(display (procedure? n))
(display (procedure? (lambda() (quote ()))))
(display (procedure? +))
(display (procedure? quit))
(display (procedure? x))
