(display (null? (list)))
(display (null? '()))
(display (null? (list 1)))
(display (null? 1))
(display (pair? (cons 1 1)))
(display (pair? (list 1 2 3)))
(display (pair? (cdr (list 1 2 3))))
(display (pair? (cdr (list 1))))
(display (pair? (list)))
(display (symbol? (quote x)))
(display (symbol?  'x))
(define x (quote x))
(display (symbol? x))
(display (number? 1))
(display (number? (+ 1 2)))
(define n 0)
(display (number? n))
(display (number? (lambda () (quote ()))))
(display (number? (list 1)))
(display (procedure? list))
(display (procedure? n))
(display (procedure? (lambda() (quote ()))))
(display (procedure? +))
(display (procedure? quit))
(display (procedure? x))
(display (symbol? 'a))
(display (symbol? 1))
(newline)
