(define fact (lambda (n) (if (= n 0) 1 (* n (fact (- n 1))))))
(define fib (lambda (n) (if (= n 1) 1 (if (= n 2) 1 (+ (fib (- n 1)) (fib (- n 2)))))))
(display (fact 1))
(display (fact 2))
(display (fact 8))
(display (fib 1))
(display (fib 2))
(display (fib 18))
