name: ASan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make ASAN="-fsanitize=address"
      run: make ASAN="-fsanitize=address"
    - name: make test
      run: make test
