name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: make test
        run: make test

  gc-stress-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: make with GC_STRESS_TEST flag
      run: make CXXFLAGS_EXTRA="-DGC_STRESS_TEST=1"
    - name: make test
      run: make test
