name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set LISP_LIB_ENV variable
      run: export LISP_LIB_ENV=./lib
    - name: make
      run: make
    - name: make test
      run: make test

  gc-stress-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set LISP_LIB_ENV variable
      run: export LISP_LIB_ENV=./lib
    - name: make with GC_STRESS_TEST flag
      run: make CXXFLAGS_EXTRA="-DGC_STRESS_TEST=1"
    - name: make test
      run: make test
